version: "3.8"

services:
  vite_docker:
    image: node:18-alpine
    container_name: vite_docker
    entrypoint: /srv/app/entrypoint.sh
    ports:
      - "8000:8000"
    working_dir: /srv/app
    volumes:
      - type: bind
        source: ./
        target: /srv/app
    tty: true